# Generated by Django 2.2.5 on 2019-09-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='parent_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='parent_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='parent_user',
            new_name='user',
        ),
    ]
