# Generated by Django 2.2.5 on 2019-09-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0005_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
