# Generated by Django 2.2.5 on 2019-10-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0007_auto_20191001_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address2',
            new_name='address',
        ),
    ]
