# Generated by Django 2.2.5 on 2019-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0008_auto_20191003_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cvv',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
