# Generated by Django 2.2.5 on 2019-10-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0009_auto_20191003_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
