# Generated by Django 2.2.5 on 2019-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0010_auto_20191003_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
