# Generated by Django 2.2.5 on 2019-10-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0011_auto_20191003_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cvv',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
