# Generated by Django 2.2.5 on 2019-10-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0018_auto_20191007_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
