# Generated by Django 2.2.5 on 2019-10-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0020_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=25, null=True)),
                ('tickets_sale_end', models.DateTimeField()),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('open_door', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
