# Generated by Django 2.2.5 on 2019-10-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0022_salles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salles',
            name='user',
        ),
    ]
