# Generated by Django 2.2.5 on 2019-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0025_remove_salles_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=25, null=True)),
                ('tickets_sale_end', models.DateTimeField(auto_now_add=True)),
                ('event_start', models.DateTimeField(auto_now_add=True)),
                ('event_end', models.DateTimeField(auto_now_add=True)),
                ('open_door', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Salles',
        ),
    ]
