# Generated by Django 2.2.5 on 2019-10-07 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yearapp', '0026_auto_20191007_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='event_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='event_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tickets_sale_end',
            field=models.DateTimeField(),
        ),
    ]
