# Generated by Django 2.2.5 on 2019-10-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0027_auto_20191007_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
    ]
