# Generated by Django 2.2.5 on 2019-10-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0029_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AlterModelTable(
            name='invitation',
            table='Invitation',
        ),
    ]
