# Generated by Django 2.2.5 on 2019-10-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0031_sale'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitation',
            table=None,
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
