# Generated by Django 2.2.5 on 2019-10-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0033_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='name_of_venue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
