# Generated by Django 2.2.5 on 2019-10-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0035_auto_20191008_0611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='SetEvent',
        ),
    ]
