# Generated by Django 2.2.5 on 2019-10-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0037_auto_20191009_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms_condition',
            field=models.BooleanField(default=False),
        ),
    ]
