# Generated by Django 2.2.5 on 2019-10-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0038_profile_terms_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='terms_condition',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
