# Generated by Django 2.2.5 on 2019-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0039_auto_20191009_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
