# Generated by Django 2.2.5 on 2019-10-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0040_auto_20191009_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setevent',
            name='invitation',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='SetEvent',
        ),
    ]
