# Generated by Django 2.2.5 on 2019-10-10 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yearapp', '0044_posting_setevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Zip',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_seller',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='business_license',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='paypal_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.CreateModel(
            name='SellerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(max_length=25)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('billing_address', models.TextField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('Zip', models.CharField(blank=True, max_length=25, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('credit_card_number', models.CharField(blank=True, max_length=15, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=15, null=True)),
                ('cvv', models.CharField(blank=True, max_length=5, null=True)),
                ('company_logo', models.FileField(blank=True, upload_to='media')),
                ('business_license', models.FileField(blank=True, upload_to='media')),
                ('about_seller', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
