# Generated by Django 2.2.5 on 2019-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0045_auto_20191010_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerinformation',
            name='about_seller',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
