# Generated by Django 2.2.5 on 2019-10-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0046_auto_20191010_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerinformation',
            old_name='address',
            new_name='seller_address',
        ),
        migrations.RenameField(
            model_name='sellerinformation',
            old_name='city',
            new_name='seller_city',
        ),
        migrations.RenameField(
            model_name='sellerinformation',
            old_name='country',
            new_name='seller_country',
        ),
        migrations.RenameField(
            model_name='sellerinformation',
            old_name='postal_code',
            new_name='seller_postal_code',
        ),
        migrations.RenameField(
            model_name='sellerinformation',
            old_name='state',
            new_name='seller_state',
        ),
        migrations.RenameField(
            model_name='sellerinformation',
            old_name='website',
            new_name='seller_website',
        ),
    ]
