# Generated by Django 2.2.5 on 2019-10-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0047_auto_20191010_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerinformation',
            old_name='seller_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='sellerinformation',
            old_name='seller_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='sellerinformation',
            old_name='seller_postal_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='sellerinformation',
            old_name='seller_website',
            new_name='website',
        ),
    ]
