# Generated by Django 2.2.5 on 2019-10-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0050_auto_20191011_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='assigend_seat_file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='posting',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='ticketless_event',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
