# Generated by Django 2.2.5 on 2019-10-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0051_auto_20191011_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='assigend_seat_file',
            new_name='assigend_seat_chart',
        ),
    ]
