# Generated by Django 2.2.5 on 2019-10-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0052_auto_20191011_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='ticketless_event',
            new_name='ticketless_event_name',
        ),
    ]
