# Generated by Django 2.2.5 on 2019-10-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0053_auto_20191011_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='assigend_seat_chart',
        ),
    ]
