# Generated by Django 2.2.5 on 2019-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0054_remove_posting_assigend_seat_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='assigend_seat_chart',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
