# Generated by Django 2.2.5 on 2019-10-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0055_posting_assigend_seat_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerinformation',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
