# Generated by Django 2.2.5 on 2019-10-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0056_auto_20191011_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='assigend_seat_chart',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
